(ns sports-app.rive-utils
  (:require ["package:rive_native/rive_native.dart" :as rive]
            ["package:flutter/material.dart" :as m]
            ["rive-utils/rive-widget.dart" :as w]
            ["rive-utils/pulse.dart" :as p]))

(defn init-rive
  []
  (w/initialize))


(defn create-resumable
  [f interval]
  (p/CallPeriodicallyResumable .fnToRepeat f
                               .intervalMs interval))
(defn fire
  [^w/RiveWidget sm ^String s]
  (.fire sm s))
(defn make-rive-widget
      "Creates a rive native widget"
      [^double width
       ^double height
       ^String asset-name
       ^String artboard-name
       ^String state-machine-name
       &
       {:keys [hit-test-behavior
               ^m/MouseCursor cursor
               fit
               ^m/Alignment alignment
               ^double layout-scale-factor
               ^bool auto-bind]
        :or {artboard-name ""
             state-machine-name ""
             hit-test-behavior rive/RiveHitTestBehavior.opaque
             cursor m/MouseCursor.defer
             fit rive/Fit.layout
             alignment m/Alignment.center
             layout-scale-factor 1.0
             auto-bind true}}]
  (w/RiveWidget
    .width width
    .height height
    .assetName asset-name
    .artboardName artboard-name
    .stateMachineName state-machine-name
    .hitTestBehavior hit-test-behavior
    .cursor cursor
    .fit fit
    .alignment alignment
    .layoutScaleFactor layout-scale-factor
    .autoBind auto-bind))

